"""
Plot predicted %% AI in the held-out test set vs. year, one connected line per
detection method.

Methods (each reads one CSV in results/):
    pangram   pangram_mpe.csv   (mean_fraction_ai | frac_pred_ai)
    pu        pu_mpe.csv        (mean_ai_prob | mpe)             -- TEDn, per year
    james     james_mpe.csv     (mpe)                            -- trained on 2020
    pn        pn_mpe.csv        (mean_ai_prob)                   -- supervised PN, 2020
    pn_platt  pn_platt_mpe.csv  (mean_ai_prob)                   -- PN + Platt scaling
Missing methods are simply skipped.

Which methods appear in a figure is just a list (`--methods`); pass a different
subset for a different figure. `--normalize` subtracts each curve's 2020 value so
every curve starts at 0 in 2020 (shows the *change* since 2020).

Four canned figures (regenerated by `--all`):
    mpe_year_plot.pdf           pangram/pu/james
    mpe_year_plot_pn.pdf        + pn/pn_platt
    mpe_year_plot_norm.pdf      pangram/pu/james,        normalized to 2020
    mpe_year_plot_pn_norm.pdf   + pn/pn_platt,           normalized to 2020

    cd .../PU_learning && python mpe_year/plot_mpe_year.py --all
    # or a single custom figure, e.g.:
    #   python mpe_year/plot_mpe_year.py --methods pangram pu james pn pn_platt \
    #          --normalize --out mpe_year_plot_pn_norm

Static matplotlib figure (PDF+PNG), consistent with the repo's other figure_*.py.
"""

import os
import argparse

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# Match the style of plot_helper/plot_temporal_alpha.py (temporal_alpha_grid.pdf):
# global bold font at size 20.
matplotlib.rc("font", **{"weight": "bold", "size": 20})

RESULTS = os.path.join(os.path.dirname(__file__), "results")
YEARS = [2020, 2023, 2025]

# Okabe-Ito colorblind-safe hues, assigned in fixed order (identity follows the
# method, never its rank). One hue per method.
COLORS = {
    "pangram":  "#0072B2",  # blue
    "pu":       "#D55E00",  # vermillion
    "james":    "#009E73",  # green
    "pn":       "#CC79A7",  # reddish purple
    "pn_platt": "#E69F00",  # orange
}
LABELS = {
    "pangram":  "Pangram",
    "pu":       "PU + TTA",
    "james":    "Liang et al. 2010",
    "pn":       "Supervised",
    "pn_platt": "Supervised Platt",
}

# Fixed categorical draw order (identity/color follow the method, never its rank).
ALL_METHODS = ["pangram", "pu", "james", "pn", "pn_platt"]


def _read(name):
    path = os.path.join(RESULTS, name)
    return pd.read_csv(path) if os.path.exists(path) else None


def series_for(method, pu_metric, pangram_metric):
    """Return (years, pct, alt_pct_or_None) for a method, or None if unavailable.
    `pct` is the predicted % AI at each year; `alt_pct` is an optional dashed
    overlay (only pu/pangram have one)."""
    if method == "james":
        df = _read("james_mpe.csv")
        col, alt = "mpe", None
    elif method == "pu":
        df = _read("pu_mpe.csv")
        col = pu_metric
        alt = "mean_ai_prob" if pu_metric == "mpe" else "mpe"
    elif method == "pn":
        df = _read("pn_mpe.csv")
        col, alt = "mean_ai_prob", None
    elif method == "pn_platt":
        df = _read("pn_platt_mpe.csv")
        col, alt = "mean_ai_prob", None
    elif method == "pangram":
        df = _read("pangram_mpe.csv")
        col = pangram_metric
        alt = "frac_pred_ai" if pangram_metric == "mean_fraction_ai" else "mean_fraction_ai"
    else:
        return None
    if df is None or col not in df.columns:
        return None
    df = df.set_index("year")
    years = [y for y in YEARS if y in df.index]
    pct = [100.0 * float(df.loc[y, col]) for y in years]
    alt_pct = None
    if alt is not None and alt in df.columns:
        alt_pct = [100.0 * float(df.loc[y, alt]) for y in years]
    return years, pct, alt_pct


def _normalize(years, vals):
    """Subtract the 2020 value so the curve starts at 0 in 2020 (change vs 2020)."""
    if vals is None:
        return None
    base = vals[years.index(2020)] if 2020 in years else vals[0]
    return [v - base for v in vals]


def _place_labels(ax, points, color_by_method, normalize):
    """Direct end-of-line labels with a light greedy de-collision so 5 curves'
    last-point labels don't overlap. `points` = list of (method, x, y)."""
    ylo, yhi = ax.get_ylim()
    gap = 0.075 * (yhi - ylo)  # min vertical separation between labels, in data units
    ordered = sorted(points, key=lambda t: t[2])  # by y ascending
    placed_y = []
    for _, _, y in ordered:
        ty = y
        if placed_y and ty - placed_y[-1] < gap:
            ty = placed_y[-1] + gap
        placed_y.append(ty)
    for (method, x, y), ty in zip(ordered, placed_y):
        val = y  # label shows the true value (2025), even after nudging position
        txt = f"{val:+.1f}%" if normalize else f"{val:.1f}%"
        ax.annotate(txt, (x, ty), textcoords="offset points", xytext=(8, 0),
                    color=color_by_method[method], fontsize=14, fontweight="bold",
                    va="center")


def make_plot(methods, out_stem, normalize=False, overlay_alt=False,
              pu_metric="mean_ai_prob", pangram_metric="mean_fraction_ai"):
    """Draw one figure for the given `methods` (a subset of ALL_METHODS).
    If `normalize`, every curve is shifted to start at 0 in 2020."""
    fig, ax = plt.subplots(figsize=(6.4, 4.6))
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)

    plotted, end_labels = [], []
    for method in ALL_METHODS:            # fixed categorical order
        if method not in methods:
            continue
        got = series_for(method, pu_metric, pangram_metric)
        if got is None:
            continue
        years, pct, alt_pct = got
        if normalize:
            pct, alt_pct = _normalize(years, pct), _normalize(years, alt_pct)
        c = COLORS[method]
        ax.plot(years, pct, marker="o", markersize=8, linewidth=2, color=c,
                label=LABELS[method], zorder=3, clip_on=False)
        end_labels.append((method, years[-1], pct[-1]))
        if overlay_alt and alt_pct is not None:
            ax.plot(years, alt_pct, marker="o", markersize=5, linewidth=1.5,
                    linestyle="--", color=c, alpha=0.55, zorder=2, clip_on=False)
        plotted.append(method)

    if not plotted:
        raise SystemExit("No results found in results/ for the requested methods.")

    ax.set_xticks(YEARS)
    ax.set_xlabel("Test Year")
    if normalize:
        # Two-line, smaller font: keep it short enough that the rotated label fits
        # inside the axes instead of overflowing up into the legend.
        ax.set_ylabel("Δ Predicted % AI\n(vs 2020)", fontsize=16)
        ax.axhline(0.0, color="0.6", linewidth=1, linestyle=":", zorder=1)
        lo, hi = ax.get_ylim()
        ax.set_ylim(bottom=min(lo, -0.02 * (hi - lo)), top=hi * 1.12 if hi > 0 else hi)
    else:
        ax.set_ylabel("Predicted % AI")
        top = max(ax.get_ylim()[1], 1.0)
        ax.set_ylim(bottom=0, top=top * 1.12)  # headroom so last-point labels don't clip
    ax.margins(x=0.06)

    _place_labels(ax, end_labels, COLORS, normalize)

    if overlay_alt and "pu" in plotted:
        ax.plot([], [], linestyle="--", color=COLORS["pu"], alpha=0.7, linewidth=1.5,
                label="PU alt")
    # Horizontal, frameless legend across the top, like temporal_alpha_grid.pdf.
    # For normalized figures the ylabel ("Δ Predicted % AI (vs 2020)") is tall and
    # reaches the top-left, so lift the legend to clear it.
    # Labels are long, so cap at 2 columns to avoid running off the figure width;
    # this trades width for extra rows. loc="lower center" grows the legend upward
    # (away from the plot), so more rows just add top whitespace, not overlap.
    ncol = 1 if len(plotted) == 1 else 2
    n_rows = int(np.ceil(len(plotted) / ncol))
    # Small extra lift per additional row so the bottom row clears the axes top
    # (matters for normalized figures, whose ylabel reaches the axes top).
    legend_y = 1.02 + 0.075 * (n_rows - 1)
    ax.legend(frameon=False, loc="lower center", bbox_to_anchor=(0.5, legend_y),
              ncol=ncol, columnspacing=1.0, handletextpad=0.5, fontsize=13)

    fig.tight_layout()
    out_pdf = os.path.join(RESULTS, f"{out_stem}.pdf")
    out_png = os.path.join(RESULTS, f"{out_stem}.png")
    fig.savefig(out_pdf, bbox_inches="tight")
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"[{out_stem}] methods={plotted} normalize={normalize} -> {out_pdf}")


# The canned figures. Each is just a (methods-subset, normalize) choice.
BASE_METHODS = ["pangram", "pu", "james"]
PN_METHODS = ["pangram", "pu", "james", "pn", "pn_platt"]
PN_NO_PANGRAM = ["pu", "james", "pn", "pn_platt"]   # 4 curves, no Pangram
PN_NO_PLATT = ["pu", "james", "pn"]                 # 3 curves, no Pangram, no Platt
FIGURES = [
    (BASE_METHODS,   "mpe_year_plot",                   False),
    (PN_METHODS,     "mpe_year_plot_pn",                False),
    (BASE_METHODS,   "mpe_year_plot_norm",              True),
    (PN_METHODS,     "mpe_year_plot_pn_norm",           True),
    (PN_NO_PANGRAM,  "mpe_year_plot_pn_nopangram",      False),
    (PN_NO_PANGRAM,  "mpe_year_plot_pn_nopangram_norm", True),
    (PN_NO_PLATT,    "mpe_year_plot_pn_noplatt",        False),
    (PN_NO_PLATT,    "mpe_year_plot_pn_noplatt_norm",   True),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--all", action="store_true",
                    help="regenerate all four canned figures")
    ap.add_argument("--methods", nargs="+", choices=ALL_METHODS, default=BASE_METHODS,
                    help="which methods to draw (single-figure mode)")
    ap.add_argument("--out", type=str, default="mpe_year_plot",
                    help="output file stem (single-figure mode)")
    ap.add_argument("--normalize", action="store_true",
                    help="subtract each curve's 2020 value (start every curve at 0)")
    ap.add_argument("--pu-metric", choices=["mpe", "mean_ai_prob"], default="mean_ai_prob")
    ap.add_argument("--pangram-metric", choices=["mean_fraction_ai", "frac_pred_ai"],
                    default="mean_fraction_ai")
    ap.add_argument("--overlay-alt", action="store_true",
                    help="also draw the alternate PU/Pangram metric (dashed, same hue)")
    args = ap.parse_args()

    if args.all:
        for methods, stem, norm in FIGURES:
            make_plot(methods, stem, normalize=norm, overlay_alt=args.overlay_alt,
                      pu_metric=args.pu_metric, pangram_metric=args.pangram_metric)
        return

    make_plot(args.methods, args.out, normalize=args.normalize,
              overlay_alt=args.overlay_alt, pu_metric=args.pu_metric,
              pangram_metric=args.pangram_metric)


if __name__ == "__main__":
    main()
